### ISSUE TITLE
Create an orphan branch

### ISSUE THREAD

**Issue by jennybc** [r-lib/gert#149]
This is basically a resurrection of #91.

The GitHub API has recently disallowed the direct use of the "magic SHA" for the empty tree, which was a pivotal piece of the workflow for creating an empty, orphan `gh-pages` branch.

It would be great if I (usethis) could accomplish this task locally with gert, then push it up to GitHub.

https://github.com/r-lib/usethis/issues/1472

**Comment by jeroen** [comment]
Asked the libgit2 authors about this. An orphan branch is a bit of a strange concept, because typically a branch is a pointer to a given commit, hence if there is no commit, there cannot be any branch. 

But we think the fix above does what the command line does. It moves the HEAD to a non-existing branch, which will then automatically be created once you commit something.

So this seems to work for me:

```r
git_branch_checkout("gh-pages", orphan = TRUE)
git_add(".")
git_commit("Commit to new branch")
```

Note that if `gh-pages` already exists, this will be checked out, i.e. no orphan is created. Also note that after the first call, the repository does not have a HEAD until you commit something.

Can you confirm if this works for you?

**Comment by jennybc** [comment]
Well, in the end I devised a new, clunkier way of doing this via the GitHub API, because I would very much like to do this entirely remotely. If I do anything locally (such as check out a branch), then I have to be extra careful to restore the original state, which creates new ways to displease a user if things go sideways.

https://github.com/r-lib/usethis/commit/5256ee8cf0aed3c0c407f4ab72a1615c25b6c92e

But the ability to create an orphan branch probably is a general feature that's worth having, with `gh-pages` being the most common use case.

**Comment by jennybc** [comment]
But I have tried to run the code you show. If I run it literally, I see:

``` r
> git_branch_create("durian", orphan = TRUE)
Error in git_branch_create("durian", orphan = TRUE) : 
  unused argument (orphan = TRUE)
```

But I assume you mean `git_branch_checkout()`?

``` r
> git_branch_checkout("durian", orphan = TRUE)
[1] "refs/heads/durian"
```

It feels like there should be some change to `git_branch_create()`, yeah? In my mind, `git_branch_checkout()` is just "create + checkout", so if I can check out a non existing orphan branch, it feels like I should be able to create and check out / not check out, too.

**Comment by jennybc** [comment]
Also: how can I create an empty commit? With this `gh-pages` task, the goal is an orphan branch, containing no files.
