### ISSUE TITLE
Need git rev-parse

### ISSUE THREAD

**Issue by jennybc** [r-lib/gert#70]
It feels like gert still needs a way to go from a general revision, possibly using various shorthands, like `HEAD` or `name-of-branch`, to a SHA (commit id).

So, the equivalent of [`git rev-parse`](https://git-scm.com/docs/git-rev-parse) in command line git or [`git2r::revparse_single()`](https://docs.ropensci.org/git2r/reference/revparse_single.html).

**Comment by jeroen** [comment]
`git_commit_info()` does that. We actually use revparse anywhere were you can specify a `ref` in gert, `git_commit_info()` gives you the commit id, and some more. We could add something that only returns the commit ID, if you'd like.

**Comment by jennybc** [comment]
Oh, glad to learn that. I tried use a ref (`master`, meaning most recent commit on `master`) in `git_cherry_pick()` and it did not work:

```
> gert::git_cherry_pick("master")
Error in libgit2::git_oid_fromstr : 
  unable to parse OID - contains invalid characters
```

which lead me to believe I had to provide a SHA (which does work).

**Comment by jennybc** [comment]
Hmm, maybe this is just `git_cherry_pick()` that requires a SHA?

**Comment by jeroen** [comment]
Right, you can only cherry-pick individual commits, not branches. To copy all commits from the entire branch, you need git-merge or git-rebase. So this is deliberate

**Comment by jennybc** [comment]
FWIW, this syntax does work with `git cherry-pick`, i.e. `master` is taken to mean the commit that `master` points to:

```
jenny@2020-mbp susan $ git cherry-pick master
[test 26d70dd] Add cherry
 Date: Tue Jun 30 13:28:05 2020 -0700
 1 file changed, 1 insertion(+)
```

**Comment by jennybc** [comment]
I suspect this might come in handy:

> `git_commit_info()` does that. We actually use revparse anywhere were you can specify a ref in gert, `git_commit_info()` gives you the commit id, and some more. We could add something that only returns the commit ID, if you'd like.

**Comment by jennybc** [comment]
By default, I sort of assume I can refer to specific commits using the methods described here:

https://git-scm.com/docs/git-rev-parse#_specifying_revisions

Of course, I only use a very narrow subset of those and I do understand some of this might not come "for free" with libgit2. So I don't expect full support for that everywhere in gert. But when it's fairly easy, it will be nice.

**Comment by jeroen** [comment]
> FWIW, this syntax does work with git cherry-pick, i.e. master is taken to mean the commit that master points to:

I had specifically disabled this because I thought maybe users would think that this would somehow cherry-pick all of master, instead of only the latest commit in the master branch. 

I would think people only use cherry-picking to merge a specific commit; if you want to merge an entire branch you would use rebase or merge. But if you think it makes sense to cherry-pick by branch name, we can change it. It's not hard to implement at all, it was a deliberate restriction.

**Comment by jennybc** [comment]
In general, the only reason I do this is because it's a PITA to get a specific SHA on the clipboard or into a command.

I feel like gert already assumes people know what they are doing, so it feels safe to assume user is doing a cherry pick with intention. So, yeah, I would remove this restriction.

But also, if this fictional `git rev-parse` wrapper existed, I could also wrap `master` with that to make the current version of `git_cherry_pick()` happy.

**Comment by jeroen** [comment]
I have added `git_commit_id()` which only does the revparsing, nothing else. You can also still use  `git_commit_info()` which gives you a bit more info about the commit (author date) in addition to the sha, cf `git2r::revparse_single()`

I like to keep the restriction that cherry-picking only applies to specific a commit, because that's what cherry picking is about. As you say, you can easily retain the previous behavior by wrapping `git_commit_id('master')` or `git_commit_id('HEAD')` and passing the sha to `git_cherry_pick()`.
