### ISSUE TITLE
Test that git_pull works for pull requests

### ISSUE THREAD

**Issue by jeroen** [r-lib/gert#76]
Because they are special refspecs

**Comment by jennybc** [comment]
Even more interesting to me is git push

I noticed a while ago that you're using those special `pr` refs on the remote.

My memory is foggy but I'm pretty sure the ability for true 2-way communication is why we took a different approach in usethis, to support the `pr_*()` functions. @jimhester and I test drove various approaches to exploring and extending PRs locally. I feel like he also brought up what you're doing, because it seems like the simplest thing to do. But then maybe those are read-only branches? And to push into the PR you must address it in the contributor's fork.

Anyhow, I would be very interested to learn that my memory is wrong. (Although I think there are other advantages to working with the contributor's fork and PR branch in the "normal" manner.)

**Comment by jeroen** [comment]
pulling is fixed via https://github.com/r-lib/gert/pull/77

From what I can tell there is no way to push directly into a pull request. You'd have to use the github api to figure out what the branch is that is being merged and try to push into that.

**Comment by jennybc** [comment]
I think that explains why we did what we did, i.e. actually add the contributor's fork as a remote. (Yes we do use the API to learn about where the PR is coming from (remote and branch))

We also try to leave the PR branch and remote configured such that user can push from the command line, from RStudio, etc. Hence we didn't want an API-based solution.

**Comment by jeroen** [comment]
Yes I agree, for a fully functional 2-way communication checkout of the PR you need the usethis approach which gets the extra information from the GH api.

For now Gert we just support the simpler case of checking out a PR locally, and `git_pull()` to get the latest commits.
